from __future__ import annotations

from PySide6.QtWidgets import QMessageBox

from core.flow_logic import (
    plan_sheets_via_dialogs,
    render_summary_text,
)

from core.edit_wo_dialog import work_orders_table_dialog
from core.docx_adapter import generate_doc_with_gui_color



class Controller:
    def __init__(self, ui):
        self.ui = ui

    def on_generate_full_flow(self):
        """
        Runs the same sequence as the old console version, but with GUI dialogs.
        DOCX layout is generated by your ORIGINAL console generate_doc() (untouched).
        """
        lot = self.ui.lot_input.text().strip()
        color = self.ui.color_combo.currentText().strip()

        if not lot:
            QMessageBox.warning(self.ui, "Missing LOT", "Please enter a LOT number.")
            return

            # 1) Enter Work Orders (table, single window)
        work_orders = work_orders_table_dialog(self.ui, None, title="Enter Work Orders")
        if work_orders is None:
            self._log("Cancelled while entering Work Orders.")
            return

        # 1.1) OPTIONAL: Modify Work Orders (same table dialog)
        want_edit = QMessageBox.question(
            self.ui,
            "Modify Work Orders",
            "Do you want to modify/edit the Work Orders before nesting?",
            QMessageBox.Yes | QMessageBox.No
        )
        if want_edit == QMessageBox.Yes:
            updated = work_orders_table_dialog(self.ui, work_orders, title="Edit Work Orders")
            if updated is None:
                self._log("Cancelled while editing Work Orders.")
                return
            work_orders = updated




        # 2) Nesting loop (allow re-nest)
        while True:
            sheets = plan_sheets_via_dialogs(self.ui, work_orders)
            if sheets is None:
                self._log("Cancelled while planning sheets.")
                return

            # 3) Show summary
            self.ui.output.clear()
            self._log(render_summary_text(work_orders, sheets))

            # 4) Ask renest?
            redo = QMessageBox.question(
                self.ui,
                "Re-nest sheets?",
                "Do you want to re-nest and re-enter sheet allocations?",
                QMessageBox.Yes | QMessageBox.No
            )
            if redo == QMessageBox.No:
                break

        # 5) Confirm generate
        do_gen = QMessageBox.question(
            self.ui,
            "Generate DOCX",
            "Generate/print the DOCX now?",
            QMessageBox.Yes | QMessageBox.No
        )
        if do_gen == QMessageBox.No:
            self._log("\n✅ Cancelled. No document generated.")
            return

        # 6) Generate DOCX using ORIGINAL layout (no changes to doc formatting)
        try:
            output_path = generate_doc_with_gui_color(
                lot_number=lot,
                work_orders=work_orders,
                sheets=sheets,
                color=color
            )
        except Exception as e:
            QMessageBox.critical(
                self.ui,
                "Error",
                f"Failed to generate DOCX:\n{e}"
            )
            return

        QMessageBox.information(
            self.ui,
            "Done",
            f"Document generated:\n{output_path}"
        )
        self._log(f"\n✅ Document generated:\n{output_path}")

    def _log(self, msg: str):
        self.ui.output.append(msg)
